---
title: "Resume"
---

# Professional Summary

I am a third year marketing student at Cal Poly Pomona. Through school I have learned how to communicate with group mates as well as understanding consumer behavior. I have a strong foundation when it comes to stepping up and leading a team. Skilled in team coordination, multitasking, planning, communication and working under pressure. m

# Education

| Degree | Year | College / Department | Institution |
|------------------|------------------|------------------|------------------|
| \[Associates Degree\] | \[2021 – 2024\] | \[Business Administration} | \[Mount San Antonio College\] |
|  |  |  |  |

# Work Experience

### \[Retail Associate\], \[Tjmaxx\]

*\[2023 – 2024\]*

-   Merchandising: Ensuring that the shelves were stocked and that the sales floor had everything needed.\
-   Customer Service: Assisting the customers with their needs, finding items, introducing the products, welcoming customers and giving them recommendations.\
-   Teamwork: Working in teams to make sure that every